[options]

; Admin password (keep as is)
admin_passwd = $pbkdf2-sha512$600000$O0dojTHmXIvx3rs3ptT6Pw$87eelAyi8LzZEQgwdi93oXAYx1SfTMSbSs/4j9xKIQtuIwVifJNrwzhtAOgj8z.nMImC9bdfWQjdgupGqnYBOQ

; Database connection (THIS is the important part)
db_host = postgres.railway.internal
db_port = 5432
db_user = postgres
db_password = gAOzODVNstslbhgIQGQrioESxBnVeZEl

; Database behavior
db_name = False
dbfilter = .*

; Addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Performance / workers
max_cron_threads = 0

; Optional
default_productivity_apps = True
