[options]
# db_host = localhost
# db_port = 5432
# db_user = odoo
# db_password = StrongPassword123
# addons_path =
#    C:\Users\mtana\Desktop\New folder\odoo111\odoo\addons,
#     C:\Users\mtana\Desktop\New folder\odoo111\odoo\odoo\addons,
#     C:\Users\mtana\Desktop\New folder\odoo111\odoo\odoo\custom_addons

# # addons_path = C:\Users\mtana\AppData\Local\odoo\addons\17.0,C:\Users\mtana\AppData\Local\OpenERP S.A\Odoo\addons\17.0,C:\Users\mtana\Desktop\New folder\odoo111\odoo\addons,C:\Users\mtana\Desktop\New folder\odoo111\odoo\custom_addons
   
# admin_passwd = $pbkdf2-sha512$600000$O0dojTHmXIvx3rs3ptT6Pw$87eelAyi8LzZEQgwdi93oXAYx1SfTMSbSs/4j9xKIQtuIwVifJNrwzhtAOgj8z.nMImC9bdfWQjdgupGqnYBOQ
# # admin_passwd = admin123

# max_cron_threads = 0

[options]
admin_passwd = $pbkdf2-sha512$600000$O0dojTHmXIvx3rs3ptT6Pw$87eelAyi8LzZEQgwdi93oXAYx1SfTMSbSs/4j9xKIQtuIwVifJNrwzhtAOgj8z.nMImC9bdfWQjdgupGqnYBOQ
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
default_productivity_apps = True
max_cron_threads = 0

