[options]
admin_passwd = $pbkdf2-sha512$600000$O0dojTHmXIvx3rs3ptT6Pw$87eelAyi8LzZEQgwdi93oXAYx1SfTMSbSs/4j9xKIQtuIwVifJNrwzhtAOgj8z.nMImC9bdfWQjdgupGqnYBOQ
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
default_productivity_apps = True
max_cron_threads = 0

